version: '3.9'
services:
  node:
    image: 'golang:1.22'
    container_name: progo
    working_dir: /app
    volumes:
      - './:/app'
    ports:
      - '8686:2020'
    tty: true
    stdin_open: true
